algorithm_name: "EWC"
num_tasks: 10
epochs: 20
lr: 0.001
hidden_dim: 100
lambdas: [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
batch_size: 200
single_head: True
seed: 100
id: 0
save_folder: "10_runs_EWC_final2"