algorithm_name: "VI"
num_tasks: 10
epochs: 10
lr: 0.001
hidden_dim: 256
batch_size: 256
mode: "regression"
single_head: False
current_window: 1
baseline_window: 50
c: 5
num_samples: 50
var: 0.01
routing_mode: "batchwise"
calculation_mode: "closed_form"
seed: 101
id: 21
save_folder: "extension_logs/routing_experiment_3"
autoencoder_hidden_dim: 1
automatic_detection: False
