algorithm_name: "VI"
num_tasks: 10
epochs: 100
lr: 0.001
hidden_dim: 100
coreset_size: 5000
coreset_heuristic: "random"
batch_size: 256
mode: "bernoulli"
single_head: True
seed: 101
id: 16
save_folder: "10_runs_vi_final"