algorithm_name: "SI"
num_tasks: 10
epochs: 400 #should be 200
lr: 0.0001 #reduce to 10^-4
hidden_dim: 500
latent_dim: 50
c: 1
damping_param: 0.1
batch_size: 256
seed: 109
id: 
save_folder: "10_runs_si_final_gen_numeric"