algorithm_name: "VI"
num_tasks: 10
epochs: 200 #should be 200
lr: 0.0001 #TODO reduce to 10^-4
hidden_dim: 500
latent_dim: 50
coreset_size: 0
coreset_heuristic: "random"
batch_size: 256
seed: 107
id: 7
save_folder: "results/generative/10_runs_gen_vi_final"