algorithm_name: "VI"
num_tasks: 10
epochs: 10
lr: 0.001
hidden_dim: 64
batch_size: 256
mode: "bernoulli"
single_head: False
current_window: 1
baseline_window: 50
c: 7
num_samples: 50
var: 0.01
routing_mode: "batchwise"
calculation_mode: "sampling"
seed: 5
id: "run_1"
save_folder: "extension_logs/routing_experiment_4"
autoencoder_hidden_dim: 1
automatic_detection: True
