algorithm_name: "VI"
num_tasks: 3
epochs: 2
lr: 0.001
hidden_dim: 32
batch_size: 256
mode : "regression"
single_head : False
current_window : 1
baseline_window : 50
c : 5
num_samples: 50
var : 0.01
routing_mode : "batchwise"
calculation_mode: "closed_form"