algorithm_name: "VI"
num_tasks: 10
epochs: 100
lr: 0.001
hidden_dim: 100
coreset_size: 200
coreset_heuristic: "random"
batch_size: 200
mode: "bernoulli"
single_head: True
coreset_only: False
seed: 100
id: 1
save_folder: "coreset_only"
