algorithm_name: "VI"
num_tasks: 10
epochs: 100
lr: 0.001
hidden_dim: 100
coreset_size: 0
coreset_heuristic: "random"
batch_size: 256
mode: "regression"
single_head: True
seed: 5
id: 1
save_folder: "10_runs_vi_final_regression"